### ISSUE TITLE
Adapter hängt sich auf

### ISSUE THREAD

**Issue by Michaelnorge** [Magnus8513/ioBroker.tibber#2]
`
<html>
<body>

tibber.0 | 2021-08-06 08:07:08.801 | error | error
-- | -- | -- | --
tibber.0 | 2021-08-06 08:07:08.336 | info | starting. Version 0.0.1 in /opt/iobroker/node_modules/iobroker.tibber, node: v14.17.2, js-controller: 3.3.15

</body>
</html>`
Der Adapter startet, und dies ist die einzige Meldung im Log (Debug)
Wenn ich mich recht entsinne hatte der Adapter vorher die Werte geholt und sich dann selbstständig runtergefahren!?

Grüße
Michael

**Comment by Magnus8513** [comment]
Habe noch zu lernen wie ein sinnvolleres error handling einzubauen ist. Das einzige was mir dazu so gerade einfällt: ist dein Token noch korrekt eingetragen? Aktuell lauft der Adapter direkt nach der Installation einmal in einen error bis er entsprechend mit einem Token uber die Instanz config gefüttert wurde.

**Comment by Magnus8513** [comment]
@Michaelnorge : could you test v0.0.2-beta please. did a lot of clean up and integrated some more advanced error logging.

**Comment by Magnus8513** [comment]
as I did not get any further feedback I assume this is fixed with most recent beta and will close this. if not,please reopen again.
