### ISSUE TITLE
Kein Wert bei "BestStart" bei Wechsel auf neuen Monat?

### ISSUE THREAD

**Issue by Michaelnorge** [Magnus8513/ioBroker.tibber#6]
Die BestStart-Abfrage hat bei mir heute versagt, nun bin ich mir nicht sicher ob es an der neuen Beta (0.3.0) oder daran liegt, daß morgen ein neuer Monat ist.

![image](https://user-images.githubusercontent.com/42386692/135486978-b2deb483-bd03-4924-91ff-f6888e01b0d9.png)

![image](https://user-images.githubusercontent.com/42386692/135487240-9b7c234c-9f5d-4388-aecd-f6c6a8ba6ee2.png)

**Comment by Magnus8513** [comment]
Danke für den Hinweis. Kann ich gerade auch so nachstellen - ich habe nicht viel Zeit gerade, schaue aber trotzdem mal kurz ob ich es debugged bekomme.

**Comment by Magnus8513** [comment]
Fehler gefunden, meine aktuelle Implementierung kommt nicht mit Monatswechseln klar - *schämt sich* - werde ich beheben, kann aber sein, dass das erst am Wochenende klappt.

**Comment by Magnus8513** [comment]
Fixed in v0.3.1-beta - dabei sind mir aber noch ein paar andere Themen aufgefallen um die ich mich kümmern sollte. Das konkrete issue, sollte damit aber behoben sein.

Bitte nochmal melden, falls doch nicht weg oder ich etwas anderes wider Erwarten verschlimmbessert habe.
